### ISSUE TITLE
Numbered Filename sorting

### ISSUE THREAD

**Issue by kaaax0815** [aperezdc/ngx-fancyindex#126] opened 2021-02-23 11:27 UTC
I have many png files generated with a for loop ({1..3000..100}) (1,101,201,301,401,501)
But when I press on "Filename" it doesnt sort right.
It sorts (1,1001,101,1101,1201,1301...2001,201,2101)

**Comment by ryandesign** [comment] 2022-05-08 23:06
Right, it sorts names using [`ngx_strcmp`](https://www.nginx.com/resources/wiki/extending/api/utility/#ngx-strcmp) which sorts in [lexographic order](https://en.wikipedia.org/wiki/Lexicographic_order). It's not surprising; many things sort that way, including the built-in nginx module autoindex.

You're asking for it to sort in [natural order](https://en.wikipedia.org/wiki/Natural_sort_order) instead. I would prefer that too, but maybe some people won't, so maybe it should be a configurable option. I don't think nginx already has a natural order sort function that ngx-fancyindex could use. Perhaps it would be beneficial to suggest the addition of such a function to the developers of nginx and to make it possible for the built-in autoindex module to use it via a configuration option. Then ngx-fancyindex will be able to use that new function too.

**Comment by ryandesign** [comment] 2022-05-09 02:18
This issue is a duplicate of #60.

**Comment by aperezdc** [comment] 2022-05-25 21:45
> This issue is a duplicate of #60.

Yes. Let's close this in favor of the other issue.

**Closed by aperezdc** 2022-05-25 21:45 UTC
Labels: enhancement
