### ISSUE TITLE
Fancyindex doesn't show all the files. 

### ISSUE THREAD

**Issue by ghost** [aperezdc/ngx-fancyindex#29] opened 2015-08-23 10:10 UTC
Hi,

I have ~30k files in a directory but fancyindex only shows ~9k. 

a `ls -R | wc -l` gives me the output of `30059`, so there's 30059 files. Browsing the directory and waiting for it to load, and then checking the source code shows that it only shows around ~9k files. Disabling Fancyindex in the conf fixes it, and all files are displayed. I recompiled fancyindex using the git version to see if that fixes it, but nope. The directory has some arabic and some unusual letters, that might have something to do with it.

My fancyindex conf:

```
fancyindex on;
fancyindex_localtime on;
fancyindex_exact_size off;
fancyindex_header "/f/header.html";
fancyindex_footer "/f/footer.php";
fancyindex_ignore "about.html";
fancyindex_ignore "contribute.html";
fancyindex_ignore "contact.html";
fancyindex_ignore "network.html";
fancyindex_ignore "sitemap.xml";
fancyindex_ignore "googlec70fa09c58ab028c.html";
fancyindex_ignore "about.html"
fancyindex_ignore "f"; 
fancyindex_ignore "robots.txt";
fancyindex_ignore "stats";
autoindex on;
try_files $uri $uri/ =404;
```

The site in question: http://bit.ly/fancyindexsite

I have another directory running on the same server, and that one has ~10k files and all of them are being displayed without any problems. I really have no idea what the problem is, has to be some kind of bug. 

Using nginx 1.9.4

Nginx -V:

```
nginx version: nginx/1.9.4
built by gcc 4.9.2 (Debian 4.9.2-10)
built with OpenSSL 1.0.1k 8 Jan 2015
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt=-Wl,-z,relro --prefix=/home/html --conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/sbin/ --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --add-module=/root/nginx-1.6.2/ngx-fancyindex --with-http_flv_module --with-http_spdy_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-ipv6 --with-http_realip_module --with-http_ssl_module --with-http_addition_module --with-debug --with-pcre-jit --with-http_stub_status_module
```

**Comment by stayn0ided** [comment] 2015-08-25 19:45
@aperezdc I'd really appreciate if you could look into this.

**Comment by aperezdc** [comment] 2015-08-25 21:36
@stayn0ided: I'm really busy for the nexy 2-3 weeks. I'll try to take a quick look in the next days, but if I cannot fix it in a couple of hours this will have to wait until mid-September. Sorry about that.

**Comment by stayn0ided** [comment] 2015-08-26 06:20
@aperezdc Much appreciated!

**Comment by stayn0ided** [comment] 2015-09-03 15:42
@aperezdc The name of the folder theme was "f", I changed it to "theme" and it now shows all the files. I also had a folder named "pdf" that it wouldn't display, after changing the name of the folder to "theme" it was being displayed as well. I'm not sure if this is a bug, or if this is indeed how fancyindex is supposed to work. But my problem is solved, and you can close this issue.

**Comment by tobbez** [comment] 2015-11-25 20:36
The documentation for the `fancyindex_ignore` directive states:

> "If Nginx was built with PCRE support strings are interpreted as regular expressions."

Looks like expected behavior.

**Comment by aperezdc** [comment] 2015-11-26 01:26
@stayn0ided: I believe that @tobbez is right and your ignore patterns are being interpreted as regular expressions. Can you try escaping the periods and adding line anchors?

The idea is that an item like:
```
fancyindex_ignore "contribute.html";
```
should be changed to:
```
fancyindex_ignore "^contribute\.html$";
```

**Comment by aperezdc** [comment] 2016-02-10 13:34
I am pretty much sure that the issue was caused by the reporter using plain strings and not being aware that the `fancyindex_ignore` directive takes regexps. Therefore, I am closing this issue for now.

Thanks again to @tobbez for noticing about the regexps.

**Closed by aperezdc** 2016-02-10 13:34 UTC
Labels: info, question
