### ISSUE TITLE
index files not working

### ISSUE THREAD

**Issue by jarischaefer** [aperezdc/ngx-fancyindex#46] opened 2016-07-31 11:15 UTC
The [index](http://nginx.org/en/docs/http/ngx_http_index_module.html#index) file seems to be ignored with nginx 1.11.2 if fancyindex is enabled. If I recall correctly, the module used to work like a drop-in replacement for [autoindex](http://nginx.org/en/docs/http/ngx_http_autoindex_module.html#autoindex) and respected the index files.

**Comment by cjmayo** [comment] 2016-08-04 19:28
For me I think this was still OK in 1.9.15 and not working in 1.10.1.

**Comment by aperezdc** [comment] 2016-08-04 19:39
It seems that I will need to find out in which version of Nginx things stopped working. One question: are you using fancyindex as a loadable dynamic module, or built into Nginx statically?

**Comment by jarischaefer** [comment] 2016-08-04 22:18
Statically

**Comment by cjmayo** [comment] 2016-08-05 19:11
Statically also. I've checked, 1.9.15 was OK.

1.9.15 was with Fancy Index 0.3.6
1.10.1 and 1.11.2 with Fancy Index 0.4.0

**Comment by tdavis** [comment] 2016-08-08 20:43
Was about to report this. FI 0.4.0 (static) with 1.10.1 ignores index.html here, as well.

**Comment by aperezdc** [comment] 2016-08-09 07:39
Thanks for all the comments. I'll check the changes introduced by Nginx and try to fix this issue as soon as I'm back from holidays later this week. Sorry for keeping you waiting!

**Comment by aperezdc** [comment] 2016-08-18 15:34
I have just started adding a test suite for the module (see #47), and I am now going to add a couple of test cases which reproduce this issue. It was about time to have tests :wink:

**Comment by aperezdc** [comment] 2016-08-18 16:34
Okay, I have an explanation for this: in versions after `1.9.11` (which introduced dynamic module support) the following piece of the `config` file is not ran:

```sh
# XXX: Insert fancyindex module *after* index module!
#
HTTP_MODULES=`echo "${HTTP_MODULES}" | sed -e \
  's/ngx_http_index_module/ngx_http_fancyindex_module ngx_http_index_module/'`
```

That is because after `1.9.11` the new system for configuring modules is used. For dynamic builds I have been already able to fix the issue by setting:

```sh
ngx_module_order="$ngx_module_name                                                                                                                                                                                                       
                  ngx_http_autoindex_module"
```

That causes the correct module order to be used when loading the module dynamically. Unfortunately for static builds the `$ngx_module_order` variable is ignored, and reordering `$HTTP_MODULES` in the way it was done before `1.9.11` does not work either. I am going through the files in `auto/*` in the Nginx source code to find out if some workaround could be used.

**Comment by aperezdc** [comment] 2016-08-18 17:28
It seems that using the old-style `config` snippet works even in recent Nginx releases when building the module statically. The following works in all supported versions:

```sh
if [ $ngx_module_link = DYNAMIC ] ; then
   # Define $ngx_module_order and source auto/module
else
   # Manually edit $HTTP_MODULES and $NGX_ADDON_SRCS
fi
```

Soon I will be pushing a fix for this issue :smile:

**Comment by aperezdc** [comment] 2016-08-18 17:41
The fix is now in `master`, and the new tests are passing in the CI. Closing.

**Closed by aperezdc** 2016-08-18 17:41 UTC
Labels: bug
