### ISSUE TITLE
Way to being able set default sorting

### ISSUE THREAD

**Issue by DerpishCat** [aperezdc/ngx-fancyindex#18] opened 2015-01-15 21:14 UTC
In Apache it's possible to set IndexOrderDefault, would it be possible to bring something similar to this module?

**Comment by archshift** [comment] 2015-02-14 21:04
This is a duplicate of #14

**Comment by aperezdc** [comment] 2015-02-18 12:55
Yes, this is a duplicate of #14

**Closed by aperezdc** 2015-02-18 12:55 UTC
Labels: duplicate
